server:
  port: 8300
spring:
  application:
    name: gits-admin
  cloud:
    kubernetes:
      discovery:
        service-labels:
          spring-boot: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'